version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Frenchfries@2005"
      MYSQL_DATABASE: expenses
    ports:
      - "3307:3306"  # Host port 3307 -> Container 3306 (avoid conflict with any local MySQL)
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expenses
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Frenchfries@2005"
      SERVER_PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "9000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:
